### PR TITLE
New filter implementation

### LINKED ISSUE #3: Loudness filter fixed for 48kHz
I think, the LUFS filter is only correct for a samplerate of 48kHz.
Should this be doing EBU-R128 prefiltering? Like the ITU filter in [Loudness Measurement according to EBU-R128 (page 13)](http://kokkinizita.linuxaudio.org/papers/loudness-meter-pres.pdf)? If yes, I have some code in my sleeve.

### PR DESCRIPTION
**Pull request by jkbd**
Here is the implementation of the EBU-R128/ITU-R BS.1770-4 filter for arbitrary samplerates.
Please check carefully, that it does not break anything.

I worked on that snippet 2 years ago...might take a while for me to wrap my head around filters again. The idea is, let `ma.SR = 48000` then the biquad-coefficients in the official recommendation will result.

This fixes #3.

### CODE REVIEW

**Comment by magnetophon** [comment]
Awesome, thanks!
Did you compare it's output with other ebu128 implementations?
If so, I'd say add some docs and do a PR to the faust libraries!

**Comment by jkbd** [comment]
I vaguely remember, that Fons does the same filter with on multiplication less, or something. But then I had to stop, due to serious real-life trouble. Give me some time to search for my notes.

**Comment by jkbd** [comment]
@x42 hints the first reference to compare with...later: https://github.com/jiixyj/libebur128/blob/67b33abe1558160ed76ada1322329b0e9e058b02/ebur128/ebur128.c#L255-L280

**Comment by magnetophon** [comment]
@jkbd We seem to be having a miscommunication:
I meant compare the measurements from your implementation to the measurements of others.

**Comment by x42** [comment]
It's just 2 Biquad Filters as per spec, not much to get wrong. Still, the proper way to verify this is by using the official tests-set from EBU:

https://tech.ebu.ch/files/live/sites/tech/files/shared/testmaterial/ebu-loudness-test-setv05.zip

**Comment by jkbd** [comment]
Ah! Thanks @x42! I'll look into that later. Since it's biquads, stability should not be an issue.

Note: The official loudness measurement contains a gate, which we don't have here.

**Review by trummerschlunk — COMMENTED** [review]
git question. Since your pr I did other modifications in the code. Will this just work merging your pr? Or will it mess up something?

**Comment by jkbd** [comment]
The Github website tells me, "no conflicts", so merging should be fine. Please wait, I will look at the filter now and will write here, when I am done.

**Comment by jkbd** [comment]
That took quiet some effort! Please have a look at my documentation. If there are no obvious mistakes, it can be merged now.

**Comment by jkbd** [comment]
The official EBU-tests-set can be used to test the whole Soundsgood plug-in. But I don't see how I could test the filter alone with it, exept the 1kHz sinewaves should be almost uneffected. I haven't tested that yet.

**Comment by trummerschlunk** [comment]
Thank you so much!! <3
Testing now... ;)

**Comment by trummerschlunk** [comment]
Bravo, almost ;)

It seems like the meter is about 0.7 below what other meters (reaper and x42) read. For all frequencies.

My guess: It's the double of your `normalize997` and `-0.691` in my code.

According to the specs, -0.691 is applied after summing. But does it matter?

**Comment by jkbd** [comment]
Are you talking decibels?
```
>>> decibel2factor(-0.691)
0.9235278572249818
```
True, that's very close to [line 72](https://github.com/trummerschlunk/soundsgood/blob/master/lib/ebur128.dsp#L72). You could adjust the normalization or remove it.

**Comment by trummerschlunk** [comment]
Yes, db.
Cool, then I'll probably go with the -0.691db from the ebu specs and drop the normalize997.

Anyways, thanks for your work - awesome !!

**Pull request merged**
