### PR TITLE
WIP: feedback leveler

### PR DESCRIPTION
**Pull request by magnetophon**
Use the output of the whole chain to detect the level.
If you like the result, I will clean up the code and get rid of the duplicated lines.

### CODE REVIEW

**Comment by trummerschlunk** [comment]
Thanks, @magnetophon , this is an idea, I was thinking about for quite some time. Very nice!

The only thing that worries me wen testing is that the out meter does not show the right value. It shows the same as the input meter of the level. Which is really weird, as I don't see any changes there...

**Comment by magnetophon** [comment]
It seems that the output meter is correct, but the input meter is displaying the level of the side-chain, which is the exact same signal as the output, so of course it will display the same value.

I guess you need to move the input meter to measure the actual input, not the side chain.

**Comment by trummerschlunk** [comment]
Ah, of course! It just measures the feedback signal now, which is the output.
I will introduce a separate input meter, which will unfortunately add more cpu cost.

**Comment by magnetophon** [comment]
At first I wanted to clean up the code by implementing the leveler without the side chain as a special case of the leveler with the side chain, but I think it makes more sense to get rid of the duplicate code by just deleting it.
We don't need the non side chain version anymore, do we?

**Comment by trummerschlunk** [comment]
Right, I will do it.

**Pull request merged**
