### PR TITLE
Extend range of LUFS meter using single float maths - #4

### PR DESCRIPTION
**Pull request by x42**

### CODE REVIEW

**Comment by trummerschlunk** [comment]
in single precision it falls to -100 at gain below -74
(faustlive macOS)

**Comment by x42** [comment]
I'm using faust2lv2 with Faust 2.41.1 on MacOS Monterey (M2)

image

**Comment by x42** [comment]
How accurate is it on your system  above -74 LUFS?

**Comment by trummerschlunk** [comment]
above -74 it's very accurate!

**Comment by x42** [comment]
I see. When I play wit the signal generator slider, move it up to 0 and then back down, the `ms_envelope_rect` limitations takes over again, and introduces an error of (ma.EPSILON).

**Pull request merged**
