### PR TITLE
adding RIAA features 

### PR DESCRIPTION
**Pull request by KoreTeknology**
it could be very useful to add RIAA EQ curve as well as inverse RIAA features, for vinyl mastering.
- The RIAA Equalization is typical of vinyl pre-amp
- The Inverse RIAA is used in vinyl record cutting
Both have standard EQ curves and specifications

### CODE REVIEW

**Comment by magnetophon** [comment]
I think something went wrong with your PR, could you take a look?
The description sounds interesting but not entirely clear, could you expand on it?

**Comment by KoreTeknology** [comment]
> I think something went wrong with your PR, could you take a look? The description sounds interesting but not entirely clear, could you expand on it?

i did update the PR, and i am open to give more technical details. thanks

**Comment by magnetophon** [comment]
This PR has 197 commits and changes 1,662 files.
I don't think that is what you intended to do.
It also makes it hard to find what you actually did.

**Comment by falkTX** [comment]
please dont push to this branch, it really is all messed up.
it has 199 commits, 1662 changed files. it basically rewrites the entire git history.

I can cherry-pick the individual good commits on the main branch. but with so many commits on this pull request i dont know which ones are actually good/useful..

**Comment by trummerschlunk** [comment]
@KoreTeknology could you please explain, what kind of RIAA features you implemented? How do you want to use master_me in a lacquer cutting process? Do you want to apply the RIAA eq to the sidechain signal in master_me and what is the benefit of this?

**Comment by magnetophon** [comment]
Shall we close this for now?
I keep getting notifications about this PR every time `master` is updated.
@KoreTeknology Feel free to re-open it when you have cleaned it up or when you can explain to us what you intend to do.

**Comment by falkTX** [comment]
I am closing it, the pull request needs to be recreated

**Pull request closed without merging**
